"""updating migrations

Revision ID: 14aaec3c599e
Revises: 2128572fbe74
Create Date: 2022-11-10 05:43:14.438514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14aaec3c599e'
down_revision = '2128572fbe74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('goal_task_id_fkey', 'goal', type_='foreignkey')
    op.drop_column('goal', 'task_id')
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    op.add_column('goal', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('goal_task_id_fkey', 'goal', 'task', ['task_id'], ['task_id'])
    # ### end Alembic commands ###
